### ISSUE TITLE
It seems there is a little mistake in ‘muse-topic_models/fine_tune_albert/README.md'

### ISSUE THREAD

**Issue by itaowei** [lstappen/MuSe2020#1]
It seems there is a little mistake in file [’muse-topic_models/fine_tune_albert/README.md'](https://github.com/lstappen/MuSe2020/edit/master/muse-topic_models/fine_tune_albert/README.md)

On line 14

Maybe we should change 

`source ./path/to/new/virtual/environment/albert/bin/active`

to

`source ./path/to/new/virtual/environment/albert/bin/activate` 

Right?

Just a a little mistake XD

**Comment by lstappen** [comment]
Fixed it. Thanks for letting us know!
